version: "3.7"
volumes:
  shared-folder:
services:
  after_deploy:
    build: ./docker-files/after-deploy
    container_name: startup-service
    environment:
      - AWS_REGION
      - SHARED_FOLDER=/data
    command: sh -c "/run-script.sh"
    volumes:
      - shared-folder:/data
