version: "3.7"
volumes:
  shared-folder:
services:
  after_deploy:
    build: ./docker-files/after-deploy
    environment:
      - AWS_REGION
      - SHARED_FOLDER=/data
    image: sanjeets/streaming-blog-after-deploy:4b91f2e
    command: sh -c "/run-script.sh"
    volumes:
      - shared-folder:/data
