version: "3.3"
services:
  neo4j:
    build: ./neo4j
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - /logs:/logs
      - /data:/data
  gremlin_console:
    build: ./gremlin_console
    ports:
      - 8080:8080
